### ISSUE TITLE
Global Threshold Node with UNSIGNEDBYTETYPE

### ISSUE THREAD

**Issue by kmader** [knime-ip/knip#103]
The global threshold node has some strange behavior when used with ```UNSIGNEDBYTETYPE``` images and thresholds above 255. It appears that the threshold (input as a double) is cast to an unsigned byte and thus if you enter a threshold like 10000, you end up having applied a threshold of 55. By default, the threshold should be either 
- limited by the maximum type value
- produce an error when it cannot be directly cast
- or turned into TYPE.MAXVALUE or TYPE.MINVALUE if it is above or below either

**Comment by dietzc** [comment]
should be fixed with: https://github.com/knime-ip/knip/commit/b439819db58038c31d1165361785b07b2061da39

can you confirm? I just started the nightly build job.
