### ISSUE TITLE
Maximumfinder throws  ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip#104]
In our  Example_Trackmate Worklflow from the websitem the Maximumfinder throws an ArrayIndexOutOfBoundsException when run.

**Comment by dietzc** [comment]
its because of the converter which is used right before the MaximumFinder. I will try to fix this.

**Comment by gab1one** [comment]
:+1: Awsome

**Comment by dietzc** [comment]
should be fixed with https://github.com/knime-ip/knip/commit/1dc09ac9621c8cc08d034f956bc651b6880d982a

**Comment by gab1one** [comment]
It is working again :+1:
