### ISSUE TITLE
Ellipse / PCA Shape Information from Segment Features

### ISSUE THREAD

**Issue by kmader** [knime-ip/knip#112]
Currently it is quite complicated to calculate orientation and the ellipsoid based model (https://rawgit.com/kmader/Quantitative-Big-Imaging-2015/master/Lectures/06-Slides.html#/36) for labels which is quite commonly used to characterize round or ellipsoid like shapes (a table-based approach is shown in part 1 in https://github.com/kmader/Quantitative-Big-Imaging-2015/blob/master/Exercises/06-Description.md). It would be nice if this were another checkbox in 'Segment Features'

**Comment by dietzc** [comment]
@DanielSeebacher can you make sure that this is part of our new node?
@kmader see: https://github.com/imagej/imagej-ops/issues/67 https://github.com/imagej/imagej-ops/tree/outputop-service

**Comment by dietzc** [comment]
@seebacherd  any comments?

**Comment by dietzc** [comment]
@tibuch make sure these features are part of any issue in the ops project.
