### ISSUE TITLE
Image Property: Source

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#115]
The image normalizer does not set the Source property.
Do you happen to have a testing framework for that? IIRC there is another node that sets only the filename instead of the path.

**Comment by maierl** [comment]
The segment cropper seems to set the filename as the source, instead of the path.

**Comment by DanielSeebacher** [comment]
Fixed in ef4f457bf2b0717d8284befa48d2186b23c5ad00.

**Comment by maierl** [comment]
The Splitter does not set the source, either.
