### ISSUE TITLE
WaveletSpotDetectionNodeModel: Setting flow-variables for threshold-factors has no influence

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip#134]
see title.

**Comment by DanielSeebacher** [comment]
I can't really reproduce the issue. The model is a little bit weird, if you want to change the third threshold factor for example, you have to change it by setting the fifth ((2 * i)- 1) flow variable. But apart from that it seems to work.

**Comment by dietzc** [comment]
can you improve the documentation, such that its more obvious (as stated in the mail of Marc).

**Comment by DanielSeebacher** [comment]
@dietzc  please check if the description is now detailed enough. can be closed afterwards.

**Comment by DanielSeebacher** [comment]
@dietzc I haven't opened a pull request for this issue. I just pushed the changes to the rc_1.4.0 branch, see commit 872aa2841a74941cf5b02f8876af1e0e3c5c4552. In my opinion a pull request isn't necessary, since I've only updated the description. There are no functional changes in this commit.

**Comment by dietzc** [comment]
oh wow this is complicated. but I think there is no way around it in the short run. thanks
