### ISSUE TITLE
ImgWriter should report or error when invalid combinations are selected instead of saving bad files

### ISSUE THREAD

**Issue by kmader** [knime-ip/knip#138]
I have noticed a number of combinations in ImgWriter do not work yet not failures are reported, simply invalid files are produced.

From a student
I use the Image Writer node and would like to save PNG filed. I have created an appropriate file name and specified the location (my Images are standard 2D microscopy images, 16bit). For some reason all the saved PNG files give the error message “File damaged” if I want to open them using another program.

**Comment by gab1one** [comment]
@kmader this is indeed troubling, could you please send me an example workflow that causes this behavior?

**Comment by gab1one** [comment]
I did not receive example images, could not reproduce this bug with other pictures.
