### ISSUE TITLE
Saving/Autosaving workflows without data

### ISSUE THREAD

**Issue by kmader** [knime-ip/knip#139]
Particularly for image workflows it would be nice to have a mechanism for saving small changes without saving all of the data (otherwise when KNIME crashes everything is lost) currently with many of my workflows there are gigabytes of data loaded and each save operation is painful and slow. It would be nice if KNIME autosaved just the nodes and their settings.

Right now I have to export workflow without data, save it somewhere and then reimport it if KNIME crashes which is not elegant.

**Comment by tibuch** [comment]
Hi @kmader 

A save without data button would be nice. As a workaround you can use the Auto Save option under

 File -> Preferences -> KNIME -> KNIME GUI called "Auto Save open workflows" and "Save with data"

**Comment by maierl** [comment]
I fully support your request. Yet another workaround that I am using quite often: you can copy & paste your whole workflow to a new one, with data getting discarded on the way.

**Comment by dietzc** [comment]
> File -> Preferences -> KNIME -> KNIME GUI called "Auto Save open workflows" and "Save with data"
isn't this what you guys are looking for?

**Comment by maierl** [comment]
For autosaving yes, but not for saving manually.

My typical use-case does not need the data to be saved with the workflow. Rather, I’d like this as an opt-in.

 

When I accidently save without having the Don’t Save Start / End nodes already, KNIME is unresponsive for hours.

**Comment by dietzc** [comment]
true. I hope compression and streaming will make this less annoying. However, this is a general KNIME feature request, therefore I suggest to ask here: https://tech.knime.org/forum.
