### ISSUE TITLE
ImageJ1 Script Node Config does not open

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#142]
On the latest nightly, the ImageJ1 Script Node Config does not open at my machine. Anyone who has the same problem?

**Comment by dietzc** [comment]
@maierl do you still experience the problem? I tried to reproduce it on windows with the latest nightly build and it seems to work just fine.

**Comment by maierl** [comment]
Seems to work just fine again, thanks!

**Comment by maierl** [comment]
Just tested it on another machine, there the ImageJ1 Config still doesn’t open.

**Comment by dietzc** [comment]
latest nightly build? freshly installed KNIME image processing?

**Comment by maierl** [comment]
latest: sure.

freshly installed: just updated. Would it be enough to merely uninstall knip within knime and reinstall it?

**Comment by maierl** [comment]
a fresh install of whole knime did the job.
