### ISSUE TITLE
Image Writer: avi / mov files

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#143]
When writing .avi or .mov files with the latest nightly, the videos have the expected length but only the first frame is displayed.

BTW: where can I find docs on the "Native QT" format? VLC says it cannot play the "twos" encoded video.

**Comment by dietzc** [comment]
@gab1one whats the status on this? post-pone to 1.4.1?

**Comment by gab1one** [comment]
Yes, this seems to be related to the other writing bugs

**Comment by gab1one** [comment]
Could not reproduce this with the current nightly. The writer results look good now.
