### ISSUE TITLE
Splitter: keep undefined cells

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#144]
Please keep undefined cells when splitting images. I have cases where the image could not be captured and would like to keep them as undefined, e.g. for the column to grid node to get an equal amount of images per case.

**Comment by dietzc** [comment]
I don't exactly know what you mean by this? Are you suggesting that, if an image has for example only two channels instead of three, that we then add a missing cell to the end of the row, if there is another image with three dimensions?

**Comment by maierl** [comment]
When I have multiple rows containing either an image or ‘undefined’, then currently the undefined values are not ‘split’, but thrown out. I’d like them to be ‘split’ just the same way as all the other images.

Especially in combination with the column to matrix node, it is important that the total number of rows does not change.

Current solution: split, outer join, sort again, column to matrix then.

**Comment by hornm** [comment]
Maybe the "Splitter (uncropped)" followed by the "Split Collection Column" is what you're looking for?
If not, please feel free to reopen this issue again.

**Comment by maierl** [comment]
thanks, i'll try that
