### ISSUE TITLE
Img Writer: write multiple columns of images

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#145]
The Image Writer should allow to write multiple columns of images, e.g. by appending or prefixing the column name to the file name given, maybe with a separator.

Maybe a bit technical, but I would prefer just to enter a Java Format string for the file name.

**Comment by gab1one** [comment]
you can do this using a column iterator loop, take a look at this (example workflow)[https://github.com/gab1one/knip-examples/releases/download/multiple-columns/Multiple.column.img.writer.example.zip]
