### ISSUE TITLE
Image Reader 'Column Selection'

### ISSUE THREAD

**Issue by seebacherd** [knime-ip/knip#151]
Every single of our image nodes has a column selection dialog where we can either choose between New Table, Append and Replace. But the Image Reader doesn't have that option. I don't know if I'm the only one needing that, but I would really appreciate if the Image Reader would also have that option, if an file name column is set. New Table works as it currently does, Replace would replace the file name column with the image and Append would only append the image to the input data.

**Comment by dietzc** [comment]
makes sense. In the future we will have two `Image Reader` nodes to avoid any confusion with the optional inport (and also to be more KNIMEIsh).
