### ISSUE TITLE
Image Reader (nightly): Settings

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#164]
An image reader node created with the stable KNIP that had the "OME-XML" option set does not have that option activated when imported in the nightly.

**Comment by maierl** [comment]
well, once again: fresh install of knime, knip nightly and all the necessary extensions solved the problem. anyway: i'd prefer that not to be necessary every few weeks.

**Comment by seebacherd** [comment]
Was already caused by 8336e670bee3417eceb6741fa0a095bab589ec45 in March. The old SettingsModel (a boolean model) was completely removed and replaced with different one, I don't really know how I could fix that. @dietzc any input?

**Comment by gab1one** [comment]
I think we should undo that commit for the old image reader. 
The new one readers will replace it and it is better to keep the old one stable.

**Comment by dietzc** [comment]
makes sense. do it.

**Comment by dietzc** [comment]
fixed.
