### ISSUE TITLE
Image writer: config

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#165]
In the latest nightly, the config pane of the image writer doesn't open.

**Comment by maierl** [comment]
I could fix that by a fresh installation of Knime, the necessary plugins, and Knip. I'd prefer it if that wasn't necessary every few weeks.

**Comment by dietzc** [comment]
you are working on the nightly build. It might be the case that you still have to do it once in a while. Use stable instead. We try to release more often.

**Comment by maierl** [comment]
that's ok :)
well, I try to use stable as much as possible, and switch only when necessary.

anyway, I'm looking forward for the next release! :+1:
