### ISSUE TITLE
Image writer: filename should allow directories

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#166]
When the "create non-existing directories" options is checked, the filename should allow sub-directories.
Another great option would be absolute paths as input option.

**Comment by gab1one** [comment]
@maierl regarding the absolute paths as input option, you can already change the output directory via flow variable. An other option is to set the output folder to your rootdirectory, and provide the paths via the name column. 
The file name field already allows subdirectories if they exist, I will look into creating the folders from the file name as well.

**Comment by maierl** [comment]
Thanks for looking into this!

Maybe I am too picky on that, but selecting the root directory is not OS independent. My own solution looks for the longest common path of the files, but that's a bit too complicated for a simple task.

**Comment by gab1one** [comment]
That is true, your proposed functionality is a good addition to the node. It  will definitively featured in the next release of KNIP.
