### ISSUE TITLE
Max Filter slowness

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#167]
I am aware that KNIME is much more general than ImageJ, but the Max Filter there executes in < 1s for my images, whereas Knime takes ~10 minutes for a radius of 20 pixels. Typically I'd just use the IJ1 macro, but that [doesn't seem to be possible from the console](https://tech.knime.org/forum/knime-image-processing/problem-with-imagej-node-if-run-from-console).

Will that get better with the IJ Ops in the next release?

**Comment by dietzc** [comment]
It will hopefully be faster.

**Comment by dietzc** [comment]
please make sure that max-filter of imagej-ops is used as soon as available.

**Comment by maierl** [comment]
is there no way this can make it to the 1.4.0? this feature is more urgent for me than almost all others scheduled for 1.4.0.

**Comment by maierl** [comment]
#181 would be a good alternative for me, if that's easier.

**Comment by dietzc** [comment]
you can use the maximum filter in Ops via the new scripting integration.

**Comment by maierl** [comment]
glad to hear that :+1:
