### ISSUE TITLE
Segment Features node - problem with label dependencies

### ISSUE THREAD

**Issue by Fritze** [knime-ip/knip#168]
Hi,

I recently ran into a problem with the Segment features node. I merge two labelings with the Labelling Arithmetic node and try to get the Label Depencies with the Segment Features Node. 
Even if there are overlapping segments, the Segment Features Node detects none of them. 
If I try again with activated "Segments do not need to completely overlap" option, everything works fine and I get the expected labelling dependencies. 
However, if I uncheck this option again and execute everything a third time, it also gives me the expected result showing all overlapping segments. Thererfore I think the overlapping option is not really the issue here.
I attach two example workflows: One shows the issue with the empty labeling dependencies column. The other was executed once with activated overlapping option and then changed back again. As explained it shows the expected labelling dependencies.  

Best,
Friedrich

https://powerfolder.dkfz.de/dl/figkASciJxVfv4nDArXcTUW/error_imagefeatures.7z

**Comment by Fritze** [comment]
I saved my "fixed" workflow (after checking and unchecking of the overlap option as explained above).
Now I am trying to run this one in the console. Again, the node does not detect any labelling dependencies.
Any ideas how to fix this?

**Comment by dietzc** [comment]
we certainly have to fix this on our side. Thanks for reporting... I will have a look and make sure that this won't happen anymore with our next release.

**Comment by dietzc** [comment]
@seebacherd can you take a look at this?

**Comment by dietzc** [comment]
@seebacherd @tibuch this should be resolved with the new `Feature Node`, right?

**Comment by dietzc** [comment]
will be solved in new feature node!
