### ISSUE TITLE
GroupBy: merge images of any dimesion

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#175]
the merge images of groupBy is a very good idea, but it should allow an arbitrary dimensionality. Last time I checked, it assumed that the new dimension is always the third.

**Comment by dietzc** [comment]
Hi @maierl can you elaborate a bit more about the use-case and the expected behaviour? it's actually not too trivial and obvious to me how to handle different sizes (in terms of empty value etc). Maybe this can be fixed using other nodes, rather than adding unclear functionality to the GroupBy?

**Comment by maierl** [comment]
we always have 3d images.

last time, I combined various sets of them so they are all normalized by the same values within those sets, but independently between the sets. now I solved it with a GroupLoop, transpose and resetting  / restoring rowIds.

another use case is to combine time series, and sometimes also channels at the same time. for that, it needs quite a few nodes to set and combine the dimension sizes for the Merger.

**Comment by dietzc** [comment]
ok, but why do they differ in dimensionality? usually in a batch environment, the image conditions don't change too much?

**Comment by maierl** [comment]
Ok, let me be a bit more exact. The GroupBy currently assumes the new dimension is always the third.
That aside, the images to be merged do have the same number of dimensions, and typically the same size in each dimension.

The new dimension may differ in size, eg I have multiple sets of 10 or 11 positions (xyzc images) that should be joined.
If merging these new images again (now they differ in the last/new dimension) would be too complicated, I think that could be circumvented and shouldn't be too bad.

**Comment by dietzc** [comment]
Ok the first part I understood and agree, the merge in the GroupBy should be more flexible. 

However, why do you have different Z-Stack sizes (curiosity, we can make it happen in the merger (I think).

**Comment by maierl** [comment]
The z-stacks would have the same number of slices, but I don't always pick the same number of example positions per subset. That would make e.g. 512x512x21x5 xyzc each, but a varying number of those per subset.

**Comment by dietzc** [comment]
and why do you want to merge them?

**Comment by maierl** [comment]
That would allow me to easily normalize the images with the same value per subset, so they stay comparable within those.
