### ISSUE TITLE
Joiner: endless loop

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#182]
On the nightly, I get an error of the Joiner node rather often that states that memory is low and that this may cause an endless loop. Most often, it does loop endlessly then.

Interestingly, when I cancel the execution of the joiner and manually run the Garbage Collection, freeing memory is often possible. Last time, this left me with only 3gb of 50gb memory in use.

Nevertheless, even when the memory could not be emptied, just looping infinitely is not a good idea. Probably this has to be solved at the Knime side, too.

```
WARN  Joiner               0:939:969  Memory is low. I have no chance to free memory. This may cause an endless loop.
```

**Comment by dietzc** [comment]
should be fixed in next release. thanks for reporting.
