### ISSUE TITLE
ImageReader2 Testflow: Failing due to changes in 

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip#183]
https://github.com/knime-ip/knip/commit/ec204a03d379db8937e65487e9c01805433c4fca

I think some (now deprecated nodes) have been created with node settings prior to this commit. please update workflow accordingly (e.g. re-execute or resave parts of it).

**Comment by seebacherd** [comment]
Yes, configuration problem of the deprecated node. Fixed that and uploaded the new test workflow.
