### ISSUE TITLE
Streaming Testflow fails

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip#185]
@seebacherd can you check why the flow is failing? I suppose it has something to do with the `Image Reader (From Table)` as the image dimensions are fundamentally different in the two branches (one has a time dimension with `50`. The other doesn't!

**Comment by seebacherd** [comment]
The already exectued branch of the test workflow had a bug (didn't read the time dimension). I fixed that by re-executing that branch. Now the non-streaming and the streaming branch both produce the same results.
