### ISSUE TITLE
Convex Hull: creates completely black images

### ISSUE THREAD

**Issue by Treiblesschorle** [knime-ip/knip#188]
Worked fine in knip 1.2 with the same setup. If the fill hull option is checked it only outputs zero for the whole image. Also, if fill hull is not checked throws ArrayIndexOutOfBoundsException.

**Comment by dietzc** [comment]
Can't confirm. Testflow runs smoothly. Can you provide a (minimal) example workflow which reproduces the problem? Optimally, you can use the Image Generator to generate test images.

**Comment by Treiblesschorle** [comment]
https://depot.uni-konstanz.de/cgi-bin/exchange.pl?g=qxvw6m3xgv

**Comment by dietzc** [comment]
fixed in https://github.com/knime-ip/knip/commit/6e7f094370699d676e0ec08430d9a99363bf235b
