### ISSUE TITLE
Cannot read labeling with Labeling Arithmetic node

### ISSUE THREAD

**Issue by Fritze** [knime-ip/knip#194]
Hi,

I recently ran into a problem with the labeling arithmetic node. I want to merge two different labelings. However, sometimes I get a nullpointer execption saying that KNIME 'can not read labeling'. I include an example workflow together with the corresponding data. Checking/Unchecking the 'virtually extend' box gives me two different error messages. I think that the spheroid labeling data was damaged earlier in the workflow (during the connected component analysis), however everything works fine until I use this segmentation again. 

Any ideas?

https://powerfolder.dkfz.de/dl/fiGL9cUB9h4Ky2V74TZ3GPek/cannot_read_labeling.7z

**Comment by dietzc** [comment]
Hi @Fritze! Thanks for reporting the bug. Can you tell us your KNIP/KNIME version?

**Comment by Fritze** [comment]
KNIME Analytics Platform	2.12.0.0048122
KNIME Image Processing	1.3.0.201508111623

**Comment by dietzc** [comment]
Hi @Fritze,

As you already said, something seems to go wrong earlier, potentially during the serialization of the `Labeling` in another node. Is the problem reproducible on your machine and can you tell me how to reproduce it?  It would be easier for me to debug the problem if I know how to reproduce it. 

Thanks!!

Christian
