### ISSUE TITLE
Make all nodes Streamable

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip#195]
* [x] Image Calcualtor
* [ ] Splitter
* [x] SetImageMetadata

**Comment by dietzc** [comment]
and 
* [ ] Image Calcualtor

**Comment by seebacherd** [comment]
Splitter would take too much time to be included in the 1.4.0 release. Changing the milestone to 1.4.1.

**Comment by dietzc** [comment]
* [ ] Feature Calculator
