### ISSUE TITLE
Unique Column Names

### ISSUE THREAD

**Issue by tibuch** [knime-ip/knip#206]
Every node should generate unique column names. To ensure unique column names one can use some util-classes from KNIME. 

Example Code:
Only one column:
```
String uniqueColumnName = DataTableSpec.getUniqueColumnName(inputSpec, "newColumnName");
```

More than one column:
```
UniqueNameGenerator ung = new UniqueNameGenerator(inSpecs[0]);
DataColumnSpec uniqueColumn = ung.newColumn("newColumnName", StringCell.TYPE);
```

**Comment by tibuch** [comment]
Nodes with unique column name support:

* KNIME Image Processing
  * IO
    * Other
      * [ ] Convolution Kernel Creator
      * [ ] Image File Linker
      * [ ] Image Importer (deprecated)
      * [ ] Structuring Element Creator 
    * [ ] Image Generator
    * [ ] Image Reader
    * [ ] Image Reader (Table)
    * [ ] Image Writer
  * Image
    * Binary
      * [ ] Binary Image Operations
      * [ ] Convex Hull
      * [ ] Distance Map
      * [ ] Fill Holes
      * [ ] Morphological Image Operations
    * Filters
      * [ ] Anisotropic Diffusion
      * [ ] Average Filter
      * [ ] Bilateral filter (rename to Bilateral Filter)
      * [ ] Convolver
      * [ ] Gaussian Convolution
      * [ ] Max Filter
      * [ ] Max Homogeneity
      * [ ] Median Filter
      * [ ] Min Filter
      * [ ] Quantile Filter
      * [ ] Sigma Filter
      * [ ] Sobel Filter
      * [ ] Variance Filter
    * Misc
      * [ ] Compare Segments
      * [ ] Data Row to Image
      * [ ] Don't Save End
      * [ ] Don't Save Start
      * [ ] Image to DataRow
      * [ ] Slice Loop End
      * [ ] Slice Loop Start
    * Process
      * [ ] Multilevel Thresholding
      * [ ] Align image
      * [ ] CLAHE
      * [ ] DoG Spot Detection
      * [ ] global Thresholder
      * [ ] Grayscale Reconstruction
      * [ ] Image Calculator
      * [ ] Image Cropper
      * [ ] Image Normalizer
      * [ ] Inverter
      * [ ] Local Maxima for Distance Map
      * [ ] Local Thresholding
      * [ ] Maximum Finder
      * [ ] Projector
      * [ ] Spot Detection
      * [ ] Thinning
      * [ ] Ultrametic Contour Map
      * [ ] h-Dome Extraction
    * Metadata
      * [ ] Dimension Cleaner
      * [ ] Dimension Extender
      * [ ] Set Image Metadata
      * [ ] Transfer Image Metadata
    * [ ] ImgPlus to PNG Images
    * [ ] Auto Crop
    * [ ] Dimension Swapper
    * [ ] Image Converter
    * [ ] Image Resizer
    * [ ] Image to Labeling
    * [ ] Merger
    * [ ] PNG Image to ImgPlus
    * [ ] Rotation 2D
    * [ ] Splitter
    * [ ] Splitter (uncropped)
    * Labeling
      * [ ] Apply Color Settings To Labels
      * [ ] Connected Component Analysis
      * [ ] Extract Outline Labeling
      * [ ] GraphCut 2D
      * [ ] Interactive Annotator
      * [ ] Interactive Labeling Editor
      * [ ] Label Transformer
      * [ ] Labeling Arithmetic
      * [ ] Labeling Converter
      * [ ] Labeling Cropper
      * [ ] Labeling Filter
      * [ ] Labeling to Image
      * [ ] Labeling to PNG Image
      * [ ] Labeling to RGB Image
      * [ ] Labeling to String based Labeling
      * [ ] Morphological Labeling Operations
      * [ ] Seed Generator
      * [ ] Seeded Watershed
      * [ ] Segment Cropper
      * [ ] Voronoi Segmentation
      * [ ] Waehlby Cell Clump Splitter
    * Features
      * [ ] Image Features
      * [ ] Image Properties
      * [ ] Image Segment Features
      * [ ] Labeling Properties
      * [ ] Segment Features
      * [ ] Feature Extractor
    * Views
      * [ ] Image Parameter Adjuster
      * [ ] Image Viewer
      * [ ] Interactive Segmentation View
    * ImageJ2

**Comment by dietzc** [comment]
while going through all nodes, please make sure that the "appendix" label is set correctly and dimensions are also selected as default.
