### ISSUE TITLE
Feature Calculator (BETA): Problems with Filters

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#238]
one can only remove one overlapping segment label filter at a time. the config window has to be closed, reopened and only then another filter can be removed.

**Comment by dietzc** [comment]
you mean the `Feature Calculator (BETA)`?

**Comment by maierl** [comment]
Yes.

**Comment by tibuch** [comment]
This pr https://github.com/knime-ip/knip/pull/280 should have fixed that. 

Sorry, I didn't checked for issues back then.
