### ISSUE TITLE
Image Calculator Configuration Window: dynamic positioning of control elements doesn't work correctly

### ISSUE THREAD

**Issue by Treiblesschorle** [knime-ip/knip#242]
If you resize the Configuration Window of the Image Calculator the positioning of the control elements only works when you make the window bigger. When making it smaller the elements stay at their position and a scrollbar appears.

http://snag.gy/GnmNp.jpg

**Comment by hornm** [comment]
Fixed with 1dab8c9092df381c6b64133b500ba2286e179c8e by just setting a static preferred size. Maybe not the perfect solution but does the job.
