### ISSUE TITLE
Image Resizer: Takes a long time to cancel

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip#264]
After canceling a running __Image Resizer__ Node it can take a long time until the node actually stops.
Maybe we can add more calls to ``exec.checkCanceled()``??

**Comment by tibuch** [comment]
@gab1one I don't think that we can improve much here. Take a look at the calls: https://github.com/knime-ip/knip/blob/master/org.knime.knip.base/src/org/knime/knip/base/nodes/proc/resizer/ResizerNodeFactory.java#L272-321

**Comment by dietzc** [comment]
this is more a future ops issue
