### ISSUE TITLE
Parallel reading of images: metadata

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#275]
When reading images in parallel (parallel chunk loop), the metadata occasionally is wrong / missing.

**Comment by dietzc** [comment]
Do you have an example workflow for that?

**Comment by beschu** [comment]
I could sadly not reproduce this error. An example workflow where this error occurs would be really helpful.

**Comment by maierl** [comment]
Sorry, these days I have to concentrate on writing. I'll come back to the issues as soon as I have the time.



Lorenz Maier
intelligent imaging at eilslabs
PhD student

German Cancer Research Center (DKFZ)
BioQuant Center (BQ 20, Room 302)
Im Neuenheimer Feld 267
D-69120 Heidelberg
Germany
phone: +49 6221 54-51296<tel:+49%206221%2054-51296>

l.maier@dkfz.de<mailto:l.maier@dkfz.de>
www.dkfz.de<http://www.dkfz.de/>
ibios.dkfz.de<http://ibios.dkfz.de/>

[cid:image001.png@01D23103.BA314620]

Management Board: Prof. Dr. Michael Baumann, Prof. Dr. Josef Puchta
VAT-ID No.: DE143293537
