### ISSUE TITLE
Rotate2D: Strange(?) behaviour

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip#277]
see https://tech.knime.org/forum/knime-image-processing/rotation-2d

**Comment by beschu** [comment]
I added the possibility to choose between radian and degree as recommended. 

However as for now, I couldn't reproduce the strange behaviour where the image turned yellow as described in the forum.
I tried it on Windows 10 with a .jpg. If I rotate an image with the Image Viewer of Windows 10 the image doesn't show as a rotated image in Knime (as described by the guys in the forum). But if I then rotate it with the Rotation 2D node it doesn't turn yellow as described by them.
