### ISSUE TITLE
ColumnFilter: Allow to filter columns by ImgPlus/Labeling type 

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip#278]
see https://tech.knime.org/forum/knime-users/feature-request-filter-by-type-image

**Comment by dietzc** [comment]
needs to be double-checked with KNIME 3.2.0 nightly and our current nightly if it works now.

**Comment by hornm** [comment]
Works well with nightly build (3.2.0). Very simple testflow (knime://knime.mountpoint/Testflows/trunk/ImageProcessing/knip/KNIME_testing_ColumnFilterByType) uploaded, just in case.
