### ISSUE TITLE
Interactive Annotator: Can't switch between columns

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip#288]
see above

**Comment by gab1one** [comment]
Probably related, one can not switch between rows using the buttons:
<img width="326" alt="screen shot 2016-02-11 at 1 52 12 pm" src="https://cloud.githubusercontent.com/assets/1938154/12988532/cfb47ab4-d0c6-11e5-9f29-93cc30487387.png">
The number changes but the row does not.

**Comment by AndreasBurger** [comment]
@gab1one That is intended, as the dialog does not fire a valueChanged event when switching between columns within a row. Therefore I assumed changing columns is not intended.
Considering @dietzc's message I'll look a bit closer.

**Comment by AndreasBurger** [comment]
Fixed.
