### ISSUE TITLE
Global Thresholder: allow a min- and a max-value as manual threshold values

### ISSUE THREAD

**Issue by hornm** [knime-ip/knip#290]
... or even more fancy: allow one to specify multiple intervals

**Comment by imagejan** [comment]
It would also be great to allow a manual threshold selection using a *column* input instead of a simple value. That would allow to use variable thresholds per row without the need of setting up a chunk loop and populating a variable in every cycle.

**Comment by dietzc** [comment]
you can already do that using flow-variables.

**Comment by hornm** [comment]
With just one node?

**Comment by dietzc** [comment]
I was refering to @imagejan.
