### ISSUE TITLE
Crashing nodes when img minimum is set: Dimension Extender and Image Cropper

### ISSUE THREAD

**Issue by hornm** [knime-ip/knip#294]
If the Dimension Extender is used on a list of 2D-bitmasks (e.g. the ones produced by the HCS-Example-Workflow) an AIOOBE is thrown.

TODO: provide test case!

**Comment by dietzc** [comment]
maybe related to `min` and `max` settings of the `BitMask`.

**Comment by hornm** [comment]
Fixed.

Testflow updated: knime://COMMUNITY/Testflows/trunk/ImageProcessing/knip/KNIME_testing_ExtendDimension
