### ISSUE TITLE
Segment Cropper: Allow virtually expansion of labeling

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip#304]
If the incoming labeling is only 2D and the image is 3D then the labeling should be optionally expanded to the size of the 3D image.

**Comment by imagejan** [comment]
I agree this would be a _very_ useful addition. As well for the Feature Calculator, e.g. if you want to measure a given part of a tissue slice acquired as z-stack.

**Comment by dietzc** [comment]
@tibuch high prio. reuse option from `Image Calculator`

**Comment by dietzc** [comment]
fixed with https://github.com/knime-ip/knip/commit/8bc4c355ad5fb43526af4a8135f3bbbfb764b451
