### ISSUE TITLE
Mismatch between offsets and image dimensions

### ISSUE THREAD

**Issue by imagejan** [knime-ip/knip#311]
When trying to montage a bunch of images (e.g. 640x540) into a big image using the GroupBy node with Compose Image aggregation, I noticed that I have to set the offsets to _half_ the tile dimensions (e.g. 320 and 270 in this example) to get the desired result. Did I misunderstand how offsets work, or is this a bug?

_Note_: I used a black image with the total dimensions (`tilesX * width`, `tilesY*height`) created by Image Generator as an interval input, to generate equally sized outputs even if some montages are missing the first or last rows of tiles. Don't know if that makes a difference.

**Comment by hornm** [comment]
Thanks for reporting, Jan! It's indeed indeed a bug.

I fixed the problem with commit cfb245f7e216e8493a9d76e89f2b7fb56d9ae563
For documentation: testflow provided - knime://knime.mountpoint/Testflows/trunk/ImageProcessing/knip/KNIME_testing_GroupBy

**Comment by imagejan** [comment]
@hornm Great, thanks a lot! :+1: 

Will these changes be deployed with a 1.4.x release on the Stable/Trusted update sites, or only with the 1.5.0 release? Just curious to know when I'll have to update my workflows to get rid of the workaround I'm currently using ;-)

**Comment by hornm** [comment]
Bug fixes will be released with minor releases (i.e. 1.4.x), hopefully soon.
