### ISSUE TITLE
Interactive Annotator UI going blank when clicking on Image Info

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip#312]
### Steps to reproduce:

- Open Interactive Annotator Dialog
- Click on __Image Info__
- View UI going blank
- Closing the Image Info will restore the UI

### Screenshots
<img width="284" alt="before" src="https://cloud.githubusercontent.com/assets/1938154/13608974/a0250fba-e51c-11e5-9249-61faa27ecdf8.png">
<img width="297" alt="after" src="https://cloud.githubusercontent.com/assets/1938154/13608976/a17cad78-e51c-11e5-9ba3-2e2cbf74cb4a.png">

**Comment by AndreasBurger** [comment]
Fixed, See #343.
