### ISSUE TITLE
Interactive Thresholder [new feature]

### ISSUE THREAD

**Issue by Luuklag** [knime-ip/knip#314]
Wouldn't it be nice to be able to threshold just like ImageJ does, with sliders over the values of the channels, instantly showing a preview of your segmentation. Currently when I want to do a segmentation I first go to ImageJ to find the appropriate values, and then enter them into KNIME. I think it would be possible to also implement this in KNIME, more or less similiar to the Interactive Annotator.

**Comment by dietzc** [comment]
Hi @Luuklag,

This is certainly something want to have in KNIP2. With KNIP2 and the imagej-ops integration you will be able to preview your settings in most of the nodes. Stay tuned!

Christian

**Comment by hornm** [comment]
You could also use the 'hacky' node "Image Parameter Adjuster". 
The usage: execute the node and open the "Interactive Adjustment View". In that view you can, for instance, then interactively set a threshold. To finish you selection click on "Set parameters and continue execution ..." at the bottom. The set parameters are propagated as flow-variables.
