### ISSUE TITLE
Interactive Segmentation View: changing bounding box color displays box names

### ISSUE THREAD

**Issue by imagejan** [knime-ip/knip#316]
When using the **Bounding Box Renderer** and changing the color of the boxes (_Set BoundingBox Color_, btw: a space should be inserted to be consistent within the UI), the names of all bounding boxes will be shown. To remove the names, you have to enable and then disable the checkbox _Show Bounding Box Names_.

**Comment by AndreasBurger** [comment]
> Set BoundingBox Color, btw: a space should be inserted to be consistent within the UI

Done.

> To remove the names, you have to enable and then disable the checkbox Show Bounding Box Names.

Fixed.

I also tweaked the layout a bit to increase the space allotted to the labels in front of the buttons.
All these changes are contained in commit 25a1a55bc3df5fc1692b24f1c330e7559d48dda1
