### ISSUE TITLE
Feature Nodes: throws NullPointerException for non-overlapping segments

### ISSUE THREAD

**Issue by imagejan** [knime-ip/knip#321]
The Feature Calculator (in the current nightly build, 1.4.2.201603140602) throws `NullPointerException` for segments without any overlap when the _Append labels of overlapping segments_ option is checked. The non-overlapping segments consequently are missing from the results table.

Here's an example workflow:
[FeatureCalculator_tests.zip](https://github.com/knime-ip/knip/files/178163/FeatureCalculator_tests.zip)

**Comment by tibuch** [comment]
Currently the provided workflow runs.
