### ISSUE TITLE
Image reader fails when spaces are in the path

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip#330]
There seems to be an issue if the path to a file read with the reader contains spaces. Might be related to #285

**Comment by gab1one** [comment]
- Can't reproduce bug on linux with the either the dialog or the table reader.

**Comment by Marckobudo** [comment]
I had the issue on a Mac and the path was insanely long: /Users/bickle/Desktop/Cellectricon/ImageRegistration/Alignment Test Data/160401_NewDataSet/GU_102_2_2x/GU 102_2 2x 1500 ms__2016-03-31T14_22_26-Measurement1/Images. 

Here is the folder with just two images, maybe you can reproduce the folder name and see whether it works.
Thanks,
Marc
[Images.zip](https://github.com/knime-ip/knip/files/223103/Images.zip)

**Comment by Marckobudo** [comment]
I have reproduced the error on a PC too.

**Comment by gab1one** [comment]
@Marckobudo I could not reproduce the error on Windows 10, but I fixed  a similar bug which might be related. The fix is available in the next nightly build, could you please test it? 
Instructions on how to install it are available here https://tech.knime.org/wiki/knime-image-processing-nightly-build

**Comment by Marckobudo** [comment]
Hi Gabriel,

As I mentioned on github, I was able to reproduce the problem on a Windows machine (don’t know the version though). Did you try to reproduce the exact path? I believe it has also to do with the length. 
I’ll check your fix and let you know.

Bye,
Marc


Marc Bickle, PhD
Head HT-Technology Development Studio
Max Planck Institute of Molecular Cell Biology and Genetics
Pfotenhauerstr. 108
D-01307 Dresden
Germany




phone   +49 351 210 2595
fax     +49 351 210 1689
mail  bickle@mpi-cbg.de
web: http://www.mpi-cbg.de/facilities/profiles/ht-tds.html

**Comment by dietzc** [comment]
@gab1one any news on that?

**Comment by gab1one** [comment]
I did not get an news from @Marckobudo and the bug never manifested in my tests.
I did clean up the path checking code.

**Comment by maierl** [comment]
Just ran into the same problem on Ubuntu 14.04, first on Knime 3.1.2 and then also after updating to Knime 3.2 and latest KNIP trunk:
```
java.io.IOException: Can't resolve file URI "file:/home/lorenz/MicData/2016%2007%2009%20round%201.1/#knime/preview.czi" to file
```

**Comment by maierl** [comment]
trying to read the same file with List Files > Image Reader (table) using its path produces
```WARN  Image Reader (Table) 0:1664     Encountered exception while reading image: /home/lorenz/MicData/2016 07 09 round 1.1/#knime/preview.czi! view log for more info.
DEBUG Image Reader (Table) 0:1664     Encountered exception while reading image:
java.lang.IllegalArgumentException: URI has a fragment component```
but with its URL, the image reade finally reads the image.

**Comment by dietzc** [comment]
I think the problem is the `#` in your foldername, not the spaces.

**Comment by maierl** [comment]
probably you are right, then that's a closely related bug.
it's not a strong reason, but I keep prefixing folders with # if I want them sorted on top.

**Comment by dietzc** [comment]
OK. I found a workaround, it was not too easy. Nightly build should ship the fix tomorrow https://github.com/knime-ip/knip/commit/97f0084d2c3c1dfd45e6116428e9bed8ef591a8a

**Comment by maierl** [comment]
Thanks!
