### ISSUE TITLE
Image Reader flips y axis when reading .ids files

### ISSUE THREAD

**Issue by imagejan** [knime-ip/knip#333]
When opening a (32-bit float) `.ids` files (output of Huygens Pro deconvolution) with _Image Reader_ (or _Image Reager (Table)_), the resulting image is flipped on the y axis.

I noticed this when comparing to the same file opened in Fiji via Bio-Formats, and when comparing to `.stk` files (of which the `.ids` file was derived) that open correctly with Image Reader, so the issue seems to be specific to `ids` files. I can send an example file (~40 MB) privately if required.

**Comment by dietzc** [comment]
Hi @imagejan,

thanks for reporting! Can you check if ImageJ in modern mode (using SCIFIO) produces the same erroneous results? 

Thanks!!

Christian

**Comment by imagejan** [comment]
You're right, @dietzc, this seems to be a SCIFIO bug. I get different result in Fiji with SCIFIO activated and deactivated.

So this issue should be moved to SCIFIO then: https://github.com/scifio/scifio/issues/301

**Comment by dietzc** [comment]
thanks @imagejan

**Comment by imagejan** [comment]
Is the plan to ship KNIP 1.5 with a new version of SCIFIO? In any case, I'd love to be notified when this issue is actually fixed, because I had to add a workaround flip to a workflow that would now break things after fixing...

**Comment by dietzc** [comment]
1.5 will ship new SCIFIO as well as our nightly build as soon as SCIFIO fixed it.
