### ISSUE TITLE
Image Reader: Drag & Drop of unknown formats

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip#334]
If I drag&drop a strange/unknown format file, e.g. sas7bdat, then the image reader is created on the workbench. this shouldn't happen!

**Comment by gab1one** [comment]
Currently the image reader is registered on all the extensions mentioned on the bioformats page:
https://www.openmicroscopy.org/site/support/bio-formats5.1/supported-formats.html

I will remove ones that are ambiguous like : ``.dat``

**Comment by dietzc** [comment]
Thanks!
