### ISSUE TITLE
Interactive Annotator: side panel too large with active Info view

### ISSUE THREAD

**Issue by imagejan** [knime-ip/knip#343]
When using the _Interactive Annotator_ node and opening the _Info_ section in the sidebar, the Minimap and the Labels and Toolbox buttons disappear behind the right border of the window frame (see attached screenshots). To fix this, either wrap lines in the _Info_ tab, or autoresize the sidebar whenever one of the sections/tabs is opened/closed.

Initial view:
![annotator_initial](https://cloud.githubusercontent.com/assets/2033938/15771472/4b06d386-296b-11e6-842d-3957472c3144.png)

After opening the _Info_ section:
![annotator_info-open](https://cloud.githubusercontent.com/assets/2033938/15771479/6210ca50-296b-11e6-8b3a-21aeb3648d3f.png)

After resizing the sidebar:
![annotator_resized](https://cloud.githubusercontent.com/assets/2033938/15771492/750c73ac-296b-11e6-808c-78ceb36c663d.png)

**Comment by imagejan** [comment]
Sorry, I just noticed that this is a duplicate of https://github.com/knime-ip/knip/issues/312. Please feel free to close either of the two issues :smile:

**Comment by AndreasBurger** [comment]
This bug should be fixed in the next release - the info panel is back at the top of the image.
