### ISSUE TITLE
Data Row to Image lets later nodes fail

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#348]
Images generated with the Data Row to Image node seem to behave strangely: Auto Crop doesn't crop (did I configure it correctly?), Segment Cropper crops but shows Image only in preview and Image Calculator fails with "Incompatible IterationOrders" error.

Knime: 3.1.2, KNIP: 1.4.1.201604050950

[data_row_to_image.zip](https://github.com/knime-ip/knip/files/299350/data_row_to_image.zip)

**Comment by dietzc** [comment]
thanks for reporting. should bot work with tomorrows nightly build.

**Comment by maierl** [comment]
works for me, thanks for your quick help!
