### ISSUE TITLE
Move to ImageJ-Ops: Boundary/Contour Tracing Algorithms 

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip#35]
see text

**Comment by DanielSeebacher** [comment]
Contour Tracing is already implemented in imagej-ops (see https://github.com/imagej/imagej-ops/blob/outputop-service/src/main/java/net/imagej/ops/geometric/polygon/DefaultMooreContoursOp.java) but the pull request (https://github.com/imagej/imagej-ops/pull/110) is still open.

**Comment by dietzc** [comment]
yes. but we have to make an explicit PR for that as soon as https://github.com/imglib/imglib2-roi/pull/13 has been merged or an alternative for this exists.

**Comment by dietzc** [comment]
done
