### ISSUE TITLE
Image preview with RGB renderer

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#351]
Last time I checked, my previews were generated by the RGB renderer. Is it possible to re-enable that feature with the current (trunk?) of KNIP?

**Comment by maierl** [comment]
any idea when this will be possible again?

**Comment by maierl** [comment]
How is the preview renderer chosen currently? I did see colored previews again, but I don't know why they were gone in the first place.

**Comment by dietzc** [comment]
it depends on your last dimension. is it working now as expected?

**Comment by maierl** [comment]
ok, thanks. if I run into the problem again, I'll check that first.

**Comment by dietzc** [comment]
thanks!

**Comment by maierl** [comment]
there it is: [png preview.zip](https://github.com/knime-ip/knip/files/470250/png.preview.zip)
tested with 3.2 stable.

**Comment by dietzc** [comment]
@hornm did your fix in #450 solve this problem, too?

**Comment by gab1one** [comment]
I just tested it with the example workflow from @maierl and it works:
![example](https://cloud.githubusercontent.com/assets/1938154/22738062/1ae82fd2-ee06-11e6-9deb-e084e2af5a9f.png)
