### ISSUE TITLE
Compose Image should keep dimension labels

### ISSUE THREAD

**Issue by imagejan** [knime-ip/knip#376]
When using _GroupBy_ with the _Compose Image_ aggregation method and no preallocated interval, the dimension labels get lost (i.e. set to Unknown). I noticed this when creating a montage of several XYC tiles.

(Tested with `KNIME Image Processing	1.5.1.201607120642` from the Nightly update site ;)

**Comment by hornm** [comment]
Well, they actually don't get lost because it's not well defined what labels to take. From the first image of the list? But that one, e.g. can have less dimensions than the result image.
Any suggestions?

**Comment by imagejan** [comment]
Hm, you compose the image with known dimensions of each source image and additionally some new dimensions that might be introduced by the offsets. The dimensions of the source images don't get altered, do they?
In my understanding, the way the result image is created is deterministic, so the result dimensions should be as well, no? Maybe I misunderstood the complexity of different use cases.

**Comment by hornm** [comment]
Yes, you're right but the labels could potentially vary, what is rare though. I fixed it and if now different labels occur at the same dimension index, they are joined together by ','. Not super helpful, but in this case the user at least gets an idea what's going on. 
But in short for you ;) - should work with the next bugfix release ...
(pull request https://github.com/knime-ip/knip/pull/378)

**Comment by dietzc** [comment]
fixed
