### ISSUE TITLE
Transfer Image Metadata: differing dimensions break metadata

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#381]
when the metadata of an XYZC image is replaced with a XYZ image by the Transfer Image Metadata node, reading the resulting metadata with an Image Properties node fails with `java.lang.IllegalArgumentException: number of provided axes != number of dimensions`

**Comment by dietzc** [comment]
which is correct. because you can't transfer the metadata from an XYZC image to an XYZ image. Use the `Dimension Extender`  before.

**Comment by maierl** [comment]
Did that then, but it should not just produce broken data, but show an error.
