### ISSUE TITLE
Set Image Metadata does not set source

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#382]
tested in KNIP 1.5.0.201607071447

**Comment by maierl** [comment]
extending an XYZ image to XYZC and using the Transfer Image Metadata doesn't set the Source, either.

**Comment by dietzc** [comment]
sorry, I don't get it. So there are two bugs? Is it important to extend the image before for the second one?

**Comment by dietzc** [comment]
https://github.com/knime-ip/knip/commit/50de6c7b52e898c6e313acc61078e377afa6987c fixed

**Comment by maierl** [comment]
thanks! that fixes both problems I assume?

**Comment by dietzc** [comment]
yes
