### ISSUE TITLE
Merging images with GroupBy discards the Source.

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#386]
after merging (mean or merge) images with GroupBy, the source property is lost.

**Comment by dietzc** [comment]
one question will be. what will the source of several images be?

**Comment by maierl** [comment]
at least if they are all the same I'd like to get that source again

**Comment by maierl** [comment]
a unique list (if multiple) with "[a, b, c]" or just the last one with a warning would be ok, too.
especially if the source starts with "[", it is obvious that care is needed when trying to rely on that programmatically.

**Comment by hornm** [comment]
Fixed with 95e0a5813c26bca3f01f2ee4796feedb7d58d564.
Image names and sources are now concatenated with "," if they are not the same over all images.

**Comment by maierl** [comment]
Thanks!
