### ISSUE TITLE
Segment Cropper synchronized after reset

### ISSUE THREAD

**Issue by manugunkel** [knime-ip/knip#395]
After a reset or a new loop iteration, all Segment Cropper nodes in a workflow generate identical output although they are configured to work on different segmentations. Changing the configuration once, closing the configuration and then set it back produces the right output but is unfavorable within a loop.
KNIME Analytics Platform	3.2.1.v201608190927
KNIME Image Processing	1.5.1.201608031220
Win 10

**Comment by dietzc** [comment]
Hi @manugunkel,

thanks for reporting this problem. Can you provide an example workflow and detailed steps how we cna reproduce the problem? This would help a lot!!

Thanks,

Christian

**Comment by manugunkel** [comment]
Hi Christian,

the problem dissapeared. I thought it was persistent and had tested it several times, that's why I reported here. I changed the workflow to circumvent the problem. After changing back the Segment Cropper nodes show the intended and right behaviour so I'm not able to reproduce.

Sorry to bug you!!

**Comment by manugunkel** [comment]
Hi Christian,


ich glaug ich hab das Problem eingegrenzt, es tritt in diesem Workflow 
ständig auf bei allen möglichen Knoten und liegt daran, dass ich die 
Bilder und Label variablenbasiert umbenenne. Dann hat natürlich der 
entsprechende IP-Knoten nicht von vornherein den Bildnamen für die 
Auswahl und führt ein auto-configure image column aus - obwohl die Namen 
jedes mal gleich sind. Bei dieser Autokonfiguration wird dann immer das 
erste passende Element gewählt und der Output ist somit gleich trotz 
vorheriger unterschiedlicher Konfiguration.


Viele Grüße


Manuel


Am 13.09.2016 um 18:13 schrieb Christian Dietz:

**Comment by gab1one** [comment]
Hi @manugunkel,
You can control the column selection using flow variables, so it should possible to always select the same column even with changing table specs. E.g using a string input node where you enter the column name.

**Comment by manugunkel** [comment]
Thanks Gabriel, I'll give it a shot!


Am 14.09.2016 um 11:20 schrieb Gabriel Einsdorf:

**Comment by manugunkel** [comment]
Perfect, solves the problem since I have the variables containing the 
respective names either way :)


Am 14.09.2016 um 11:20 schrieb Gabriel Einsdorf:

**Comment by gab1one** [comment]
I am glad I could help :smiley_cat:.
