### ISSUE TITLE
Normalize images for Thumbnails?

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip#396]
The fact that our thumbnails are not normalized confuses users [for example here](https://tech.knime.org/forum/knime-image-processing/problem-with-image-writer-node), because the result of node operations seems to be a black image. We could  normalize the thumbnails, to prevent this.

**Comment by imagejan** [comment]
See also https://github.com/knime-ip/knip/issues/359

**Comment by dietzc** [comment]
black or grey image @gab1one. We actually can easily enable normalization for all thumbnails. @hornm what do you think? Anyway, duplicate of #359.
