### ISSUE TITLE
New Node: Image Segment Features

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip#40]
New node using imagej-ops feature implementations. Should be based on knip-scijava

**Comment by dietzc** [comment]
@DanielSeebacher  Some suggestions from users:

 [  ] Selected features should be minimizable. In the minimized view a short overview over the selected features might be given. 
 [  ] Column Selection should be moved to own tab. 
 [  ] Dimension Selection for each FeatureSet. Min/Max restricted to the dimensions which can be calculated.
 [  ] Select / Deselect all features in one FeatureSet.
 [  ] 

thanks @maierl for the feedback.

**Comment by maierl** [comment]
one more thing: it would be great if this new node used the cpu more efficiently than the old one. as yet, cpu usage on my 8-core is at only 3% with 10 lanes in parallel.

**Comment by maierl** [comment]
Not sure if you still accept bugs for the old node, but that one can only remove one overlapping segment label filter at a time. the config window has to be closed, reopened and only then another filter can be removed.

**Comment by DanielSeebacher** [comment]
@maierl The new node will fully support multithreading, but is currently still WIP. I'm trying to get it running as fast as possible. As for the bug report for the old node, I'm not sure if we will fix that or not, since the node will be replaced by the new feature node.

**Comment by dietzc** [comment]
open points:
[ ] https://github.com/imagej/imagej-ops/issues/67. make sure all of these features are implemented and tested.
[ ] provide benchmarks (comparison against old node, analysis where performance is lost etc).

**Comment by dietzc** [comment]
More suggestions:
* [ ] Allow output of average for haralick-features.
* [ ] Find nice solution for current `LabelingFilter` implementation (avoid usage of too many nodes!!!!!!!).
* [ ] Testflow

**Comment by dietzc** [comment]
TODOs: 
* [ ] Append original input on selection (and also create correct spec) @tibuch 
* [ ]  Append label information if desired @tibuch 
* [ ] Filter labels if wanted, else ignore filtering

* [ ] Multi-threading over LabelRegions @dietzc
** Use futures to make sure that order stays the same!!

* [ ] Make Geometric3DFeature working again @seebacherd
* [ ] Local Binary Patterns Feature Set
* [ ] Weighted Centroid Feature Set
* [ ] Geometric2D (use simple features = non polygon features) if possible
* [ ] StatFeatures: Add optimizations (e.g. calc min/max in one run)

* Add description to all features and use in UI 
* Regression tests with features of former node
* Test ALL feature sets and all combinations of Img+Labeling
* Move node into proper directory
* Rename node to Feature Calculator
* Remove dependency (and the jar) as soon as imagej-ops 0.21.1 was released.
* Nice XML description
* Testflow
* Exampleflow

* Optional: Dialog improvements.

**Comment by seebacherd** [comment]
all done. @dietzc Center of Gravity and Centroid still don't work. They would need an input during configure() which is null at that point.

**Comment by dietzc** [comment]
Thanks! I will take care of that!!

**Comment by dietzc** [comment]
one thing I forgot: we have to add the `FeatureSet` for image moments (hue, centralized, normalized etc).

**Comment by seebacherd** [comment]
No we don't. This feature set was already added in db71138.

**Comment by dietzc** [comment]
Pure awesomeness ;)

**Comment by gab1one** [comment]
there is still a nullpointer when trying to use the center of gravity feature
	``org.knime.knip.features.sets.CenterOfGravityFeatureSet.getFeatures(CenterOfGravityFeatureSet.java:78)``

**Comment by dietzc** [comment]
we are not done with the refactoring,yet. I will let you know (tomorrow).

**Comment by gab1one** [comment]
:+1:

**Comment by dietzc** [comment]
@gab1one @Treiblesschorle I just merged the node. You can create a test-flow, example flow etc and test the node tomorrow. The testflow should comprise a test for each feature set, regression sets. and many misconfigurations should be checked (3D Geometric + 2D Dim Selection etc). Let me know if you find bugs or if some stuff is not intuitive etc.

@tibuch @seebacherd the xml description is very poor at the moment. a lot of components are not well explained. could you change that?

**Comment by seebacherd** [comment]
@dietzc Nodefactory.xml or the description in the info dialog?

**Comment by dietzc** [comment]
the NodeFactory.xml. I just pushed some more fixes. Node should be working now! Thanks!!

**Comment by seebacherd** [comment]
I can try if I can fit that in my schedule, but I'm away till monday. I most likely have to delegate this responsibility to @tibuch.

**Comment by dietzc** [comment]
all right. let's see who ever is first ;-)

**Comment by tibuch** [comment]
I added an improved description.

**Comment by dietzc** [comment]
beta released
