### ISSUE TITLE
AssertionError on Max Z Projection

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#403]
After both Knip 3.2 stable and the nightly somehow again came up with the error that images are not shown / updated after a few clicks (I set the Image Annotor config, closed it, reloaded and no images were shown anymore), now I resorted to the 3.2 stable SDK.

That one gives me an assertion error on the Projector node.
[assertion_error.knwf.txt](https://github.com/knime-ip/knip/files/495955/assertion_error.knwf.txt)

**Comment by dietzc** [comment]
thanks for reporting! fixed in https://github.com/knime-ip/knip/commit/47be4328b6a0e369fcd49ccd50081cf5732631f2.

About the first error: If you can reproduce this behaviour, please open a dedicated issue. I'm happy to help then!

**Comment by maierl** [comment]
that was super fast, thanks @dietzc !
