### ISSUE TITLE
Interactive Annotator: blocking after removed polygon

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#405]
When I enter a polygon shape in the Interactive Annotator and remove it, I cannot enter a polygon shape again for 5-10 seconds. there is no apparent CPU load during that time, though.

**Comment by dietzc** [comment]
puh, I can't reproduce this one. can you try again with the latest nightly and let me know if the error is still present?

**Comment by maierl** [comment]
that bug is dodgy... happened in 100% for my old dataset, but cannot reproduce on a smaller one so far.
I suspect it is related to the number of polygon annotations that already exist for that dataset, maybe even if the current image has an entry in the annotator already.
Closing until I find the core of that bug.
