### ISSUE TITLE
Interactive Annotator: permanent defunct on malpositioned rectangle

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#406]
When I use the interactive annotator to create a new rectangle annotation that accidentally crosses the top edge of the image, it stops to react on any click until I reload the whole workflow.

Even changing the Z-position of the image does not work anymore then.

[Example workflow](https://github.com/knime-ip/knip/files/497510/annotator_fail.zip)

**Comment by maierl** [comment]
another version of this bug:
- create a polygon annotation
- use the selection tool to move its topmost point beyond the top edge of the image

-> never finishes executing anymore

**Comment by maierl** [comment]
another, but non-critical bug when clicking outside of the image:
- start polygon
- click outside the image
- polygon remains as single line and polygon creation is stopped

**Comment by dietzc** [comment]
I think I fixed all three bugs by ignoring _all_ clicks outside the image. can you test the next nightly and tell me if you are satisfied with the behavior?

Thanks again for reporting. This is super helpful!

**Comment by maierl** [comment]
sure, I'll have a look. the fix sounds good.
The second bug doesn't need a click outside the image, however: you can just move the shape outside at the top when you hold its bottom.

**Comment by dietzc** [comment]
Ok, I'm ignoring _any_ action outside the image ;-)

**Comment by maierl** [comment]
On 1.5.2.201610010712, trying to create a rectangle that crosses the image boundaries still blocks the whole node.

**Comment by dietzc** [comment]
oversight from my side. should be fixed with next nightly in ~2h.

**Comment by maierl** [comment]
bugs 1 + 2 are fixed 👍 , just the non-critical bug 3 remains.

**Comment by maierl** [comment]
btw @dietzc: do you get notified when I edit a comment?

**Comment by dietzc** [comment]
unfortunately not. Can you quickly outline what is bug1, bug2, bug3? I'm a bit lost :-) thanks!

**Comment by maierl** [comment]
bug 1: first one mentioned on this thread, fixed.
bug 2:
>
- create a polygon annotation
- use the selection tool to move its topmost point beyond the top edge of the image (tested with 2 points outside of image)
- execute
-> never finishes executing

bug 3:
>
- start polygon
- click outside the image
- polygon remains as single line and polygon creation is stopped

**Comment by dietzc** [comment]
great! I worked a bit on it. https://github.com/knime-ip/knip/commit/57c4f1f25bcb9b5788e58cd101c50316b45e4b70

Can you test the annotator? I changed quite a lot ... should make drawing easier in general!

**Comment by maierl** [comment]
Looks good to me 👍 . I also like how you handle the polygon clicks outside the image.

One last thing though: the annotations I created with earlier versions are not restored. Unfortunately, I put quite a lot of effort into those lately. Could you maybe make them importable to the updated annotator?

**Comment by maierl** [comment]
newest commit fixed that, thanks!
