### ISSUE TITLE
Image Reader: Allow to read in subsets of series

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip#41]
see: http://tech.knime.org/forum/knime-image-processing/feature-request-image-reader-read-multiple-series

**Comment by dietzc** [comment]
https://github.com/knime-ip/knip/blob/master/org.knime.knip.io/src/org/knime/knip/io/nodes/imgreader/ReadFileImgTable.java

**Comment by dietzc** [comment]
@seebacherd can we close this issue?

**Comment by seebacherd** [comment]
@maierl I've kinda added the functionality to the new image reader (you can select min and max index and it reads everything in between) but I need an image to verify if the functionality is working. Do you have an example image for me?

**Comment by maierl** [comment]
@seebacherd there it is: https://powerfolder.dkfz.de/dl/fiJEgZVx2rLg85FP96JvJ66p/IP-Create_Image_Subset-01.czi

**Comment by dietzc** [comment]
@seebacherd fixed?
