### ISSUE TITLE
Interactive Annotator: ask to save on close

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#413]
Pressing the "X" button to close the Annotator should ask if changes shall be saved instead of discarding them instantly.

**Comment by dietzc** [comment]
this is a general concept in KNIME, which we can't solve on our side. please reach out to the KNIME core team directly in the KNIME forum.

**Comment by maierl** [comment]
Well, ok then.

**Comment by maierl** [comment]
There you go: https://tech.knime.org/forum/knime-users/ask-to-save-node-settings-on-close
