### ISSUE TITLE
Improve documentation on segment filter rules

### ISSUE THREAD

**Issue by imagejan** [knime-ip/knip#460]
It's not really clear to me from the node descriptions whether the rules for **filter on segment labels** as well as **filter overlapping segment labels** in the _Segment Cropper_ and _Feature Calculator_ nodes take regular expressions or wild cards, or if that behavior can be configured in any way, similar to the _Row Filter_ node.

By trial and error with the _Feature Calculator (BETA)_ downstream of an _Interactive Annotator_ node, I noticed that:
* a filter rule like `Segment: \d+` works,
* a filter rule like `Segment*` as well, but
* `Segment.*` produces an empty table, despite being a valid regex to match e.g. "Segment: 1"

It would be nice if that was clearly documented somewhere, or if the choice would be left to the user, just like in the _Row Filter_ and other KNIME core nodes.

**Comment by imagejan** [comment]
I also wonder why this is necessary:

https://github.com/knime-ip/knip/blob/8aa1488e09dafcbdfca903fd9ed4ed67d24e5efd/org.knime.knip.core/src/org/knime/knip/core/ui/imgviewer/events/RulebasedLabelFilter.java#L283-L298

Isn't that conflating wildcard and regex syntax? At least in some cases, it breaks correct regex matching.

**Comment by tibuch** [comment]
@imagejan thanks for pointing it out! I opened a PR which should fix this. 

The new dialog works now like the Row Filter node and looks like this:
![image](https://cloud.githubusercontent.com/assets/5450869/24202734/193a7918-0f14-11e7-847f-76e2e5f03b57.png)
