### ISSUE TITLE
Image Reader: Slowness when network drive is connected

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip#468]
see https://tech.knime.org/forum/knime-image-processing/image-writer-cannot-write-to-network-drives#comment-48710

**Comment by imagejan** [comment]
Image Reader?? The linked forum post talks about Image Writer and file permissions, not slowness.

Related issues are: https://github.com/knime-ip/knip/issues/336 and https://github.com/knime-ip/knip/issues/131

**Comment by dietzc** [comment]
brr. thanks @imagejan. I need sleep
