### ISSUE TITLE
Labeling to PNG Images: transparency parameter is misnamed.

### ISSUE THREAD

**Issue by imagejan** [knime-ip/knip#480]
In the *Labeling to PNG Images* node, the *Transparency of labels* parameter should actually be *Opacity of labels*, because that's what it is, and what the description says (255 means opaque):

https://github.com/knime-ip/knip/blob/8aa1488e09dafcbdfca903fd9ed4ed67d24e5efd/org.knime.knip.base/src/org/knime/knip/base/nodes/seg/labeltopng/LabelingToPNGValueNodeFactory.xml#L21-L23

**Comment by gab1one** [comment]
Thank you for noticing, I fixed it, should be in the next nightly release.
