### ISSUE TITLE
Percentile Normalizer

### ISSUE THREAD

**Issue by HedgehogCode** [knime-ip/knip#482]
For our project, we need a percentile normalizer. This means:
* Calculate two given percentiles of all image values e.g. 2nd and 98th percentile
* Normalize mapping the first percentile to 0 and the second to 1
* __Optionally__ clamp values below 0 and above 1

Should I write a new node and should this node go into knip?
Is there a nice solution using existing nodes?

**Comment by imagejan** [comment]
You can do it with existing nodes, but it's a bit convoluted: you need to map the actual image min and max to target min and max as follows:
```
                       max - lowerPercentile
targetMax <=  -------------------------------------
                upperPercentile - lowerPercentile

                      upperPercentile - min
targetMin <=  -------------------------------------
                upperPercentile - lowerPercentile
```

You can use the metanode in the attached workflow to do this:

[Percentile Normalization.zip](https://github.com/knime-ip/knip/files/1384580/Percentile.Normalization.zip)

---

If you think there should be a dedicated (native) node for it, I'd suggest to create an Op as generic as possible in `imagej-ops` and just provide an appropriate wrapper node (if at all, provided that KNIP2 is supposed to auto-generate nodes for ops at some point, right?)

**Comment by HedgehogCode** [comment]
Nice workaround. I didn't think about using the target min and max to avoid clamping. Your workflow works great!
For now, I will do the same. And later I will write an Op and maybe get a nice dedicated node from KNIP2. (The thing was, that I have no time waiting for KNIP2)

I think I can close this issue for now. Thank you @imagejan!
