### ISSUE TITLE
Mixed up sigma values in DoG Spot Detection node

### ISSUE THREAD

**Issue by imagejan** [knime-ip/knip#492]
In the description of the *DoG Spot Detection* node, it says:

https://github.com/knime-ip/knip/blob/92633c9c672bac47c5981496f4fd790ba74d900a/org.knime.knip.base/src/org/knime/knip/base/nodes/proc/dogdetector/DoGDetector2NodeFactory.xml#L35-L38

So far so good, but now if you want to replace the config dialog values with workflow variables, you actually have to choose `sigma2_value` for *Sigma 1* and `sigma1_value` for *Sigma 2* to get the expected results. This is due to this inconsistency between UI and implementation here:

https://github.com/knime-ip/knip/blob/92633c9c672bac47c5981496f4fd790ba74d900a/org.knime.knip.base/src/org/knime/knip/base/nodes/proc/dogdetector/DoGDetector2NodeFactory.java#L88-L93

**Comment by gab1one** [comment]
Well spotted, thank you for the report 👍 Already fixed on master

**Comment by imagejan** [comment]
@gab1one with the latest nightly build, I see that the _DoG Spot Detection_ node (in saved workflows) shows as deprecated (which is fine), but there's no _DoG Spot Detection_ entry discoverable in the Node Repository any more.
I don't quite understand the naming scheme, but it might be related to this? Why are there `DoGDetector2NodeFactory3.java` and `DoGDetector3NodeFactory.xml`, and is the link between them supposed to be auto-discovered?

**Comment by gab1one** [comment]
Jan, I am sorry for the inconvenience and many thanks for the very helpful feedback.
Seems I was working a bit too fast on the issue and made a few mistakes. They should be all fixed now.

**Comment by imagejan** [comment]
Thanks, @gab1one. May the force-push be with you ;-)
