### ISSUE TITLE
Image Viewer: Merged view

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#56]
It would be great if there was a merged + color table based view.
In Zeiss Zen blue, I can select for each of N channels which of them should be shown in an overlay.

Additionally, the black and white value (= min and max shown) and the gamma per channel can be set by adjusting the line on the histograms within the screenshots. The first and last box shaped handle of the line modifies the black and white value, respectively. The middle handle modifies them both at once like sliding a window. The second and fourth handle do not move left and right as the others, but up and down and they modify the gamma value. Moreover, the black/white value can also be changed with the vertical bar at the end of the lines for convenience.

The "best fit" works as a contrast stretcher, excluding a default of 2% black pixels and 0.01% white pixels and can be applied to the current x,y(,z)?(,t)? subvolumes.

The gamma and best fit would be an optional extra, but  the merged overlay and being able to set the black/white value would help a lot!

*Update:* another optional, but handy feature is storing the image display settings (in Zen blue, they can even be copy+pasted with or without assigning colors, but I don't expect this to be necessary in Knime)

![zen_all_channels](https://cloud.githubusercontent.com/assets/8655419/4769160/c4081ac6-5b75-11e4-9a09-69d4a144a4d5.png)

![zen_green_and_red_with_gamma_and_black_value_changed](https://cloud.githubusercontent.com/assets/8655419/4769164/c9ffe5a8-5b75-11e4-9d85-967670d20fa9.png)

**Comment by dietzc** [comment]
will be fixed in #127.
