### ISSUE TITLE
WählbyCellClumpSplitter: Border Pixels are removed even if valid

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip#58]
After splitting, all segments which previously touched the border, do not touch the border anymore.

**Comment by dietzc** [comment]
did we already fix this bug @Squareys?

**Comment by Squareys** [comment]
@dietzc No, we didn't fix it yet.

**Comment by dietzc** [comment]
was this fixed already?

**Comment by Squareys** [comment]
See #299. :)
