### ISSUE TITLE
InteractiveLabelingEditor performs unnecessary calculations

### ISSUE THREAD

**Issue by AndreasBurger** [knime-ip/knip#70]
When executing, the Interactive Labeling Editor performs unnecessary calculations on images that weren't touched by the user.

**Comment by dietzc** [comment]
@AndreasBurger any news on this?

**Comment by dietzc** [comment]
@AndreasBurger can this issue be closed?

**Comment by AndreasBurger** [comment]
Since the execute-method was carried over from the previous iteration - not yet. However, due to some changes in the way the converter stores changes I'll have to look if it's still possible.

**Comment by dietzc** [comment]
can't we simply check if a `Labeling` was modified and if not we just pass the source `DataCell`to the out table?

**Comment by AndreasBurger** [comment]
Yes, however we'd need to check for each original label whether it was changed or not. So - one check, i.e. set comparison, per index.

Shouldn't be too hard, actually. I'll get right to it.

**Comment by dietzc** [comment]
what about a general `dirty flag` which is true on the first change of the incoming `ImgLabeling`?

**Comment by AndreasBurger** [comment]
Good point. Will do.

**Comment by dietzc** [comment]
:+1:

**Comment by AndreasBurger** [comment]
The necessary methods are created, however there are some type issues: Output labeling is expected to be String, however input is not restricted.
I've included a hook in the execute method - I will get to it once I figure out the necessary type-wrangling code. Alternatively, might be an easy fix for you, @dietzc .

Removing the explicit output-type-restriction is another option, I guess.

**Comment by dietzc** [comment]
@AndreasBurger did we fix this?
