### ISSUE TITLE
Table Cell Viewer: Better presentation of table and view

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#74]
It would be great if the Table Cell Viewer remembered the width of the table vs cell contents.

Moreover, there seems to be a bug when trying to change the size of the table: if I first click on the image and then try to increase the table size, the ruler does not move at all.

![table cell viewer2](https://cloud.githubusercontent.com/assets/8655419/5358055/0316e144-7fb0-11e4-8116-60cae741e868.png)

**Comment by dietzc** [comment]
@AndreasBurger I know you fixed it already, but in certain I have two of the horizontal scrollbars. maybe we can think of another concept for the table-cell-viewer? 

For example: only show the table. On click a new panel is opened with the actual image but also with four arrows to navigate in the table? Suggestions welcome.

**Comment by maierl** [comment]
Knime “core” won’t allow to extend the standard output port view with the TableCellViewer by default, I assume? I’d love that feature, though.

Besides of that, two windows that are to be used in parallel are not necessarily better than one in my eyes.
Keyboard navigation for switching between rows is (currently) already implemented, right?

@dietzc didn’t you propose that the first image should be automatically displayed without clicking on table first? Showing the image right away would seem more natural to me. Especially as the “Table Cell Viewer” view is currently selected explicitly.

**Comment by dietzc** [comment]
hi @maierl,

unfortunately, it's not too easy to get the functionality into KNIME-Core (even if I agree, it would be nice). The solution I suggested was not about "having two windows open side by side". We would still have only one JFrame, but it would more look like a gallery view. 

about "opening the first image": see https://github.com/knime-ip/knip/issues/51

**Comment by maierl** [comment]
The gallery idea seems fine to me.

**Comment by dietzc** [comment]
will be solved with new table cell viewer #127.
