### ISSUE TITLE
Force ImageType in ImgReader?

### ISSUE THREAD

**Issue by seebacherd** [knime-ip/knip#79]
Should it be possible to force the ImageReader to use a specific ImageType? To clarify, the following dataset ([patentbase](http://mklab.iti.gr/project/patentbase)) consists of 2000 binary images and has a size of 80,1 MB.

If this dataset is loaded using the Image Reader and saved, the workflow needs over 9GB of space on the hard disk, since every image is now uncompressed and of type UnsignedByteType. Since we know beforehand that we will only read binary images, we could tell the ImageReader to load the images as BitType, which should theoretically reduce the hard drive usage by one-eighth.

**Comment by dietzc** [comment]
@gab1one do you think this is possible to add this option? the user has to take care that the chosen type is suitable for her image type, if she decides to select the type manually.

**Comment by gab1one** [comment]
This should be easy to do using [this](https://github.com/scifio/scifio/blob/master/src/main/java/io/scif/img/ImgOpener.java#L215) method.

The [ScifioImgSource](https://github.com/knime-ip/knip/blob/master/org.knime.knip.io/src/org/knime/knip/io/ScifioImgSource.java) looks like it  is in dire need of refactoring, though.

**Comment by dietzc** [comment]
@gab1one @seebacherd any news on this?

**Comment by gab1one** [comment]
closed by #193
