### ISSUE TITLE
Image Parameter Adjuster: issues with channel, Z and zoom

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#85]
The Image Parameter Adjuster Node does not update the values for Z and channel. The channel variable was even beyond the image dimensions.
Zoom level is initialized with 0, but should be 1.

Thanks for your help!

**Comment by hornm** [comment]
Hm, can't reproduce. Maybe somebody fixed it already?

**Comment by maierl** [comment]
Apparently, someone did. Thanks for that.
