### ISSUE TITLE
Image Reader doesn't close File.

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip#89]
From E-Mail:

"Ich habe noch eine Frage: wenn ich mit dem Image Reader Knoten eine Datei öffne, dann kann ich in Windows nichts mit der Datei machen. Nicht umbenennen, nicht löschen und nicht überschreiben. Auch nützt es nichts, den Workflow zu schließen. Erst wenn ich KNIME geschlossen habe kann ich mit dieser Datei wieder "arbeiten"."

**Comment by dietzc** [comment]
any news on that @gab1one?

**Comment by gab1one** [comment]
Konnt ich nicht reproduzieren :/

**Comment by hornm** [comment]
Problem still exists according to this forum post: https://tech.knime.org/forum/knime-image-processing/images-loaded-with-image-reader-table-node-are-not-closed

**Comment by hornm** [comment]
fixed with bec9819fd465aaa32dd430c7e6376af6ca8bca19
