### ISSUE TITLE
Table Cell Viewer: Allow Browsing through planes with Hot-Keys

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip#91]
See: http://tech.knime.org/forum/knime-image-processing/interactive-segmentation-view

Actually this is already implemented but it seems, that it doesn't work on certain operating systems. Please check for Windows, Linux and MAC if it works and fix as needed.

**Comment by maierl** [comment]
I tested it on Windows, there it didn't work.

**Comment by maierl** [comment]
My fault, I mis-read the mail and was referring to a different issue.

**Comment by AndreasBurger** [comment]
This issue was apparently caused by the java method used to set the desired hotkey - it was too specific. I've changed the used method to accept any key which produces the required characters, '+' and '-'.
