### ISSUE TITLE
Gaussian Convolution: Allow multiple sigmas 

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip#94]
Currently, the user can only enter one sigma which is then applied for in each dimension. Actually, the sigmas could vary over the dimensions. 

Task: Add another option, which allows to enter dimension specific sigmas. This option is disabled as default, but if its enabled, the current option is disabled.

**Comment by dietzc** [comment]
@angrauma any news on this?

**Comment by dietzc** [comment]
`GaussNativeTypeNodeFactory`

**Comment by seebacherd** [comment]
Check if you're happy with the changes, issue can be closed than. Test Workflow is KNIME_testing_GaussianConvolution2.
